version: 0.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: normal
before_build:
  - nuget restore
